---
- hosts: webservers
  become: yes
  gather_facts: false
  tasks: 
  - block:
    - name: install apache2
      apt: 
       name: apache2
       state: present
    rescue:
    - debug:
       msg: "the given path is not valid"   