---
- hosts: 172.31.12.93
  become: yes
  tasks:
  - name: start
    apt:
     name: apache2
     state: present
     update_cache: yes 
  - name: staert service
    service:
     name: apache2
     state: restarted  