# In this we are going to handle the error depanding on first result, we are giving the conditions based on first result
---
- hosts: 172.31.41.86
  become: yes
  tasks:
  - name: linux commands execution
    command: hostname -f
    register: nagendra
  - name: disply the result  
    debug:
     msg: "{{nagendra}}"
  - name: install apache2
    apt:
     name: apache2
    when: nagendra.stderr ==""
  - name: install tree
    apt:
     name: tree
    when: nagendra.stderr !=""   