# remove apache using handler
---
- hosts: webservers
  become: yes
  tasks:
  - name: install apache2
    apt:
     name: apache2
     state: present
    notify: remove
  - name: install tree
    apt:
     name: tree
     state: present
    
  handlers:
  - name: remove  
    apt:
     name: apache2
     state: absent
   