# remove apache using handler
---
- hosts: webservers
  become: yes
  tasks:
  - name: remove apache2
    apt:
      name: apache2
      state: absent
    notify: remove
  - name: install tree
    apt:
      name: tree
      state: present
    notify:
    
  handler:
  - name: remove  
    apt:
     name: apt
     state: absent
   