# we can reuse the code with the help of handlers by using notify ( ubuntu)
---
- hosts: webservers
  become: yes
  tasks:
  - name: Install apache2
    apt:
     name: apache2
     state: present
    notify: remove
     
  - name: copy index.j2 to node server
    template:
     src: index.j2
     dest: /var/www/html/index.html
    notify: remove
  # under playbook we are going to write handlers 
  handlers:
  - name: start services
    service:
     name: apache2
     state: restarted   
  - name: remove
    apt:
     name: apache2
     state: absent     