# we can reuse the code with the help of handlers by using notify ( redhat)
---
- hosts: webservers
  become: yes
  tasks:
  - name: Install apache2
    yum:
     name: httpd
     state: present
    notify: start services   
  - name: copy index.j2 to node server
    template:
     src: index.j2
     dest: /etc/apache2_conf
    notify: start services
  # under playbook we are going to write handlers 
  handlers:
  - name: start services
    service:
     name: httpd
     state: restarted     