---
- hosts: localhost
  become: yes
  tasks:
  - name: linux commands execution
    command: "ls /home/ansible"            # we are executing the linux commands
    register: nagendra               # register key is used to store value
  - name: disply the result  
    debug:                           # debug is used to display the stored value of the key
     msg: "{{nagendra}}"
  - name: linux commands execution
    command: "ls /home/ansible/jana"            # we are executing the linux commands
    register: nagendra               # register key is used to store value
  - name: disply the result  
    debug:                           # debug is used to display the stored value of the key
     msg: "{{nagendra}}"    