---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: display the result
    command: "ls /home/ansible"
    register: ansible3
    debug: 
      msg: "{{ansible3}}"
  - name: output of jana    
    command: "ls /home/ansible/jana"
    register: ansible1
    debug:
      msg: "{{ansible1}}"
  - name: output of devops    
    command: "ls /home/ansible/Devops"
    register: ansible2
    debug: 
      msg: "{{ansible2}}"