---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
  - name: display the result
    command: "ls /home/ansible"
    register: ansible3
    debug: 
      msg: "{{ansible3}}"
    command: "ls /home/ansible/jana"
    register: ansible1
    debug:
      msg: "{{ansible1}}"
    command: "ls /home/ansible/Devops"
    register: ansible2
    debug: 
      msg: "{{ansible2}}"