---
- name: Install the tomcat and configure
  hosts: 172.31.35.207
  gather_facts: false
  become: yes
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
    req_tom_version: 9.0.27
    tomcat_url: http://us.mirrors.quenda.co/apache/tomcat/tomcat-{{req_tom_version.split('.')[0]}}/v{{req_tom_version}}/bin/apache-tomcat-{{req_tom_version}}.tar.gz
  tasks:
  - name: updating the repos
    yum:
      name: "*"
      state: latest
  - name: install the java
    yum:
      name: "{{req_java}}"
      state: present    
  - name: setting the java default
    alternatives:
      name: java
      link: /usr/bin/java
      path: /usr/lib/jvm/{{set_java}}/bin/java
  