---
- name: Install the tomcat and configure
  hosts: 172.31.35.207
  gather_facts: false
  become: yes
  tasks:
  - name: updating the repos
    yum:
      name: "*"
      state: latest
  - name: setting the java default
    alternatives:
      name: java
      link: /usr/bin/java
      path: /usr/lib/jvm/jre-11-openjdk/bin/java