---
- hosts: all
  become: yes
  tasks:
  - name: pinging the inventory files
    ping:
  - name: Install tree
    apt:
      name: tree
  - name: Install the apache2
    apt:
      name: apache2
  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: yes
