---
- name: This is practice session
  hosts: webservers
  become: yes
  gather_facts: true
  vars:
   ubuntu: apache2
   redhat: httpd
  tasks:
  - block:
    - name: install apache2
      apt:
        name: "{{ubuntu}}"
        state: present
      notify: start apache2
    - name: copy the index into apache2
      template:
        src: index.j2
        dest: /var/www/html/index.html
      notify: start apache2
    - name: start the apache2
      service:
        name: "{{ubuntu}}" 
        state: started
        enabled: yes 
      notify: start apache2    
    when: ansible_os_family =="Debian"
    ignore_errors: yes 
  - debug:
     msg: "successfull install the all tasks"


  - block:
    - name: install httpd in redhat
      yum:
        name: "{{redhat}}"
        state: present
      notify: start httpd 
    - name: copy the index into apache2
      template:
        src: index.j2
        dest: /var/www/html/index.html
      notify: start httpd
    - name: start the apache2
      service:
        name: "{{redhat}}" 
        state: started
        enabled: yes 
      notify: start httpd     
    when: ansible_os_family =="RedHat"
    ignore_errors: yes 
  - debug:
     msg: "successfull install the all tasks"
     
    



  handlers:
  - name: start apache2
    service:
      name: "{{ubuntu}}"
      state: restarted

  - name: start httpd  
    service:
      name: "{{redhat}}"
      state: restarted  

