---
- name: This is practice session
  hosts: webservers
  become: yes
  gather_facts: true
  vars:
   ubuntu: apache
   redhat: httpd
  tasks:
  - block:
    - name: install apache2
      apt:
        name: "{{ubuntu}}"
        state: present
      notify: start apache2
    - name: copy the index into apache2
      template:
        src: index.j2
        dest: /var/www/html/index.html
      notify: start apache2
    - name: start the apache2
      service:
        name: "{{ubuntu}}" 
        state: started
        enabled: yes 
      notify: start apache2 
    rescue:
    - name: loop
      apt:
        name: "{{item}}"
        state: present
      loop: 
      - tree
      - wget
      notify: start apache2  

    when: ansible_os_family =="Debian"
    ignore_errors: no
  - debug:
     msg: "successfull install the all tasks"


  

  handlers:
  - name: start apache2
    service:
      name: "{{ubuntu}}"
      state: restarted

  - name: start httpd  
    service:
      name: "{{redhat}}"
      state: restarted  

