---
- name: create the fine and install apache2
  hosts: all
  become: yes
  tasks:
  - name: create file
    file:
      path: /home/cm/sample.txt
      owner: cm
      group: cm
      mode: '0644'
      state: touch
  - name: install apache2
    apt:
      name: apache2
      state: latest
  - name: place sample file apache2 directory
    template:
      src: index.html 
      dest: /var/www/html
