---
- name: Install the java in ubuntu and Redhat
  hosts: ubuntuservers
  become: yes
  tasks:
  - name: Install java in ubuntu
    apt:
      name: "{{installjavaold}}"
      state: "{{webserupdate}}"
    when: ansible_os_family =="Debian"        
  - name: Install java in Redhat
    yum:
      name: "{{installjava}}"
      state: "{{javastate}}"
    when: ansible_os_family =="RedHat" 
  