---
- name: Install the tomcat and configure
  hosts: 172.31.35.207
  gather_facts: false
  become: yes
  vars:
    req_tom_version: 9.0.27
    tomcat_url: http://us.mirrors.quenda.co/apache/tomcat/tomcat-{{req_tom_version.split('.')[0]}}/v{{req_tom_version}}/bin/apache-tomcat-{{req_tom_version}}.tar.gz
  tasks:
  - name: Downloading the tomcat server
    get_url:
      url: "{{tomcat_url}}"
      dest: /usr/local  