---
- name: Install firewalld
  package:
    name: firewalld
    state: present


- name: Allow external HTTP(S) traffic
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
  notify: restart tomcat  



- name: open ports with firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ open_ports }}"
  tags:
    - open_ports