---
- name: deploy java application
  get_url:
    url: http://18.217.111.88:8081/artifactory/Deploy-java-application/2/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
  notify: restart tomcat  
