---
- name: deploy java application
  get_url:
    url: http://54.191.192.173:8081/artifactory/NAGENDRA/{{build_number}}/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
  notify: restart tomcat  
