---
- name: deploy java application
  get_url:
    url: http://34.217.33.180:8081/artifactory/myUAT/{{mybuildno}}/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
  notify: restart tomcat  
