---
- name: copy index file in ubuntu
  template:
   src: index.j2
   dest: /var/www/html/index.html
  notify: service apache2 restart
  when: "{{family_u}}"

- name: copy index file in redhat
  template:
   src: index.j2
   dest: /var/www/html/index.html
  notify: service http restart
  when: "{{family_r}}"
