---
- name: install apache2 in ubuntu
  apt:
   name: "{{install_apache_ubuntu}}"
   state: present
  notify: service apache2 restart
  when: family_u

- name: install http in redhat
  yum:
   name: "{{install_http_redhat}}"
   state: present
  notify: service http restart
  when: family_r   