---
- name: start apache2 ubuntu
  service:
   name: "{{install_apache_ubuntu}}"
   state: restarted
  when: family_u

- name: start http redhat
  service:
   name: "{{install_http_redhat}}"
   state: restarted
  when: family_r   